### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by chirukinbb** [lojadev5/opencart-phpstorm#2] opened 2021-06-14 10:05 UTC
Hi, thx for addon 
but have a problem^
$this-> autocomplete work
$this->load(or another, whitch light by autocompleter) autocomplete doesn't work
how to enable all levels for autocomlete? and possible enable in autocomplete classes of controllers and models?

**Comment by lojadev5** [comment] 2022-03-10 02:23
Foxed on

**Comment by lojadev5** [comment] 2022-03-10 02:24
Duplicate of #1

**Closed by lojadev5** 2022-03-10 02:23 UTC
